### ISSUE TITLE
Improper styling

### ISSUE THREAD

**Issue by Saachi30** [Ahsankhalid618/react-weather-app#13]
I have improved the look of the application by making it more visually appealing to users

Screenshots of changes:

Before
![image](https://github.com/user-attachments/assets/acf3ba40-0b0e-4837-865f-8c25624a4cad)

After
![image](https://github.com/user-attachments/assets/bc366efa-deef-42f3-8abd-49c1938f93d4)
![image](https://github.com/user-attachments/assets/6b0b4c09-a057-4f70-925f-41e4b0ac0a5a)

Have also added a light and dark mode toggle !!

Files changed:
- All jsx and css files

Please assign this issue to me so that I can raise a PR for the changes

**Comment by Ahsankhalid618** [comment]
Wow, your design is wonderful, but you see that with every city weather,  the background also changes, which is a good feature which i think you replaced. I am assigning this issue to you if you can just change the pink colour to transparent and add those background pics with it like glassmorphism or anything else that should persist the current UI layout and features, either enhance it, make it more beautiful but don't change the whole design at all.. anyway, comment and tell me, can you do that?

**Comment by Ahsankhalid618** [comment]
@Saachi30 Wow, your design is wonderful, but you see that with every city weather,  the background also changes, which is a good feature which i think you replaced. I am assigning this issue to you if you can just change the pink colour to transparent and add those background pics with it like glassmorphism or anything else that should persist the current UI layout and features, either enhance it, make it more beautiful but don't change the whole design at all.. anyway, comment and tell me, can you do that?

**Comment by Kuldeepagrahari** [comment]
I can give you a lot better UI , more engaging and attractive to the user, assign this issue to me

**Comment by Ahsankhalid618** [comment]
@Kuldeepagrahari Your contributions are most welcome, but FCFS, that's a standard rule of open source. I hope you understand. If you have any idea (that is a new feature or enhancement to the current features) to contribute or bug to fix, then raise a new issue you will get assigned.

Looking forward to your future contributions soon.😊

Leave a 🌟 to the repo for notifications and updates regarding new contributions. Thanks.

**Comment by Saachi30** [comment]
Working on it!! Will send a PR by tonight

**Comment by Ahsankhalid618** [comment]
> Working on it!! Will send a PR by tonight

Alright, mention the issue number in your PR and screenshots as well.
