### ISSUE TITLE
On load it will show weather of the user's current position

### ISSUE THREAD

**Issue by sujal1256** [Ahsankhalid618/react-weather-app#17]
For now, when the web page loads it shows weather data of London, 
I will use Geolocation and ReverseGeolocation API to get the current city name such that the user will see weather of current locaiton of the user.

**Comment by sujal1256** [comment]
Hey @Ahsankhalid618, Is this issue relevant to the project, If so please assign this issue to me so that I can start working on this issue.

**Comment by Ahsankhalid618** [comment]
@sujal1256 good feature, Go ahead.
Remember to fork this repo and create a new branch to start working and before you raise a PR, use Git pull to be sync with the latest changes and add a screenshot of your changes here.

*Leave a :star: on the repo and get started.*

**Comment by sujal1256** [comment]
Ok will take care about these things

**Comment by sujal1256** [comment]
I am using LocationIQ API, which required a API KEY,
I tried Google Geolocation API but it will cause problems for contributors to get their API KEY
That's why I am going with a easier one.
