### ISSUE TITLE
Search Loader Required 

### ISSUE THREAD

**Issue by xTwo56** [Ahsankhalid618/react-weather-app#23]
Currently there is no loader or any other feature present to inform user about the loading of weather data on the main page. Happy to resolve it.

https://github.com/user-attachments/assets/e11e7ac3-56c9-4a05-87b0-b58362bdbb61

**Comment by Ahsankhalid618** [comment]
@xTwo56 go ahead, add a suitable loader and make sure to add your changes screenshot here before raising a PR. Thanks

**Comment by kartik-212004** [comment]
can i work on this issue?

**Comment by Ahsankhalid618** [comment]
@xTwo56 any progress?

**Comment by xTwo56** [comment]
@Ahsankhalid618 As mentioned earlier in #34, it seems api still not activated or I am just messing up.
Did you decativate your api? I tried with yours too still I am unauthorized with 401. 
For now, I am pushing changes which were working fine before PR #20

**Comment by Ahsankhalid618** [comment]
@xTwo56 Your PR has a lot of build issues. and what do you mean by my API? You need to generate a new API for yourself on OpenWeatherMap and geolocation API, put them in a .env file, test the app, and then add the .env file to .gitignore so it should not push with other files and then raise a PR. most importantly before you push changes, try git pull so your code should be synced with the main branch..Make these changes and then again raise a PR. Thanks

**Comment by xTwo56** [comment]
@Ahsankhalid618 I meant by key which was previously available by you and yes I did generated both of them, but I am encountering a 401 error with none of my code changes suggesting maybe the keys are not activated yet, 
If possible, provide a test api key to avoid hiccups in the generation process
The build issues are absolutely on me, just can't test my code.

**Comment by Ahsankhalid618** [comment]
@xTwo56 yeah API keys take some time to activate, wait for an hour and then try, keys will be activated by then. Unfortunately, I only have a primary key which can't be shared here. and always try to check server logs, they will give you a better idea of errors. let me know if you need any help.

**Comment by Ahsankhalid618** [comment]
Thanks.
