### ISSUE TITLE
FEAT: Trigger weather search on ENTER key press

### ISSUE THREAD

**Issue by Dcoder10M** [Ahsankhalid618/react-weather-app#25]
Currently, pressing the ENTER key does not trigger any action on the weather search input field. The expected behavior is that when the user types a city name and presses ENTER, it should trigger a weather search.

**Comment by 10m4y** [comment]
@Dcoder10M I would like to contribute can u pls add hacktoberfest tag and assign it to me

**Comment by Ahsankhalid618** [comment]
@Dcoder10M Please don't open the PR without an issue assigned to you first.

**Comment by Ahsankhalid618** [comment]
@Dcoder10M I am assigning you now but before opening the PR, add a screenshot of changes here then open the PR with issue no linked, proper title, and description. Thanks

**Comment by Dcoder10M** [comment]
Can you please add the Hacktoberfest and Hacktoberfest-accepted labels?

**Comment by Ahsankhalid618** [comment]
Do follow the guidelines I mentioned above.

**Comment by Dcoder10M** [comment]
Is it fine now? @Ahsankhalid618
