### ISSUE TITLE
Page not found UI

### ISSUE THREAD

**Issue by Karan1962** [Ahsankhalid618/react-weather-app#29]
We can make page for 404 page not found.

when user is trying to visit undefined routes there is not 404 page is rendering .

I would like to contribute in this project by adding page not found UI in accordance with the projects current theme.

@Ahsankhalid618 requesting you to kindly assign this issue to me under hactoberfest .

**Comment by Ahsankhalid618** [comment]
@Karan1962 our website has only a single page so there is no point of 404 page for now at least.
