### ISSUE TITLE
Improve the UI by adjusting the position of the theme button.

### ISSUE THREAD

**Issue by Dcoder10M** [Ahsankhalid618/react-weather-app#30]
I think it's a good idea to adjust the theme button to better fit the current UI.
![image](https://github.com/user-attachments/assets/f367052d-45fc-40a8-8481-fadbddbbe4b7)

@Ahsankhalid618  Please assign this issue to me under hacktoberfest.

**Comment by Ahsankhalid618** [comment]
@Dcoder10M theme button is well placed but you can center the search bar for all screen sizes.
