### ISSUE TITLE
Unnecessary Search Calls

### ISSUE THREAD

**Issue by xTwo56** [Ahsankhalid618/react-weather-app#34]
User might click search multiple times which results in multiple fetch calls for same data.
happy to resolve this issue

ps: would've added screencast but my api keys are not activated yet

**Comment by Ahsankhalid618** [comment]
@xTwo56 you are already assigned another issue.

**Comment by xTwo56** [comment]
> @xTwo56 you are already assigned another issue.

I have resolved it, it's just my api is not activated yet, so I can't retest it
The loader was working fine before I pulled new changes
