### ISSUE TITLE
Add AQI info

### ISSUE THREAD

**Issue by anjalit03** [Ahsankhalid618/react-weather-app#42]
In the different info boxes likes wind, humidity, etc. we can also add an AQI feature.

**Comment by Ahsankhalid618** [comment]
@anjalit03 You want to work on it?

**Comment by anjalit03** [comment]
@Ahsankhalid618 Yes please assign this to me if the issue is okay with you :)

**Comment by Ahsankhalid618** [comment]
ok, go ahead. just make sure to add SS here before raising a PR.

**Comment by anjalit03** [comment]
@Ahsankhalid618 Is this alright?
![Screenshot 2024-10-31 135953](https://github.com/user-attachments/assets/1b44528d-a522-4c5a-aec8-5d215a29a77f)

**Comment by Ahsankhalid618** [comment]
The feature is good but don't you think, only one box of AQI is in 2nd row, which changes the whole layout. If you have any idea to place it somewhere else that shouldn't change the UI Layout completely

**Comment by anjalit03** [comment]
Alright!! I'll try that!!

**Comment by Ahsankhalid618** [comment]
If you are registered for Hacktberfest, Today is the last day for contributions.

**Comment by anjalit03** [comment]
@Ahsankhalid618 Is this alright? I was trying to put the temperature below the city name as well to make it look even better but I'm kind of stuck at that point :(

![Screenshot 2024-10-31 234704](https://github.com/user-attachments/assets/a02fd298-0559-4c1b-aa41-77a3328d2e44)

**Comment by Ahsankhalid618** [comment]
that could be CSS problem, do one thing, just open the PR for  the changes you made before in the previous SS I mentioned. and open a PR, I'll merge it and then later you can again open another issue for better improvement, that will help you in learning as well.

> @Ahsankhalid618 Is this alright? ![Screenshot 2024-10-31 135953](https://private-user-images.githubusercontent.com/119848677/381879832-1b44528d-a522-4c5a-aec8-5d215a29a77f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0MDA5MjAsIm5iZiI6MTczMDQwMDYyMCwicGF0aCI6Ii8xMTk4NDg2NzcvMzgxODc5ODMyLTFiNDQ1MjhkLWE1MjItNGM1YS1hZWM4LTVkMjE1YTI5YTc3Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMVQxODUwMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hODYyYzRmM2FkYTFjYTkzZTUwZjBkZDZhZjI4NGI4OTk0OWRiZWQ3NDk1MTU5Y2I1OTllMGY2MzJmNTQ2MzUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.8wiczebS4T_QCdEIP0osN-dVJ-GPw5t4oH_XUr4kT6U)

**Comment by anjalit03** [comment]
Okay I'll do that !!
