### ISSUE TITLE
City Not Found Error Shows Previous City's Forecast Information

### ISSUE THREAD

**Issue by Ncode-93** [Ahsankhalid618/react-weather-app#5]
**Description:**
When searching for a city that does not exist or is mistyped (e.g., "gunturr"), the application does not correctly handle the "City Not Found" error. Instead, it displays the weather forecast for the previously searched city (e.g., Gurugram) underneath the "City not found" message.

**How I discovered the error:**
-> Open the weather forecast app.
-> Search for a valid city (e.g., "Gurugram").
-> Now search for a non-existent or incorrect city name (e.g., "gunturr").
-> Observe the error message along with the previous city's weather forecast.

**Current Behavior:**
1) The app displays "City 'gunturr' not found".
2) However, the weather forecast for the previously searched city (Gurugram) is still visible below the error message.

**Expected Behavior:**
1) A clear error message should be shown: "City not found".
2) No weather information for the previously searched city should be displayed.

**Screenshot**

![image](https://github.com/user-attachments/assets/ab1258bf-5450-484a-a3d9-465af244cb55)

**Comment by JhoanAlvear** [comment]
hello, asigne to me this issue please

**Comment by Ahsankhalid618** [comment]
@Ncode-93 Alright, make sure to add a screenshot of your changes before you raise a PR. Fork and create a new branch and then make your changes and then push the branch as PR. Thanks
