### ISSUE TITLE
Enhance README File

### ISSUE THREAD

**Issue by Amansingh0807** [Ahsankhalid618/react-weather-app#8]
I have made significant improvements to the README file of the Weather App project to enhance its usability and accessibility.

Changes Made:

- Added Contribution Guidelines: Included detailed instructions for potential contributors.
- Highlighted Features: Created a dedicated section showcasing the app's main features.
- Outlined Future Improvements: Provided suggestions for further enhancements to the project.
- Acknowledgments: Recognized the contributions of the open-source community and OpenWeatherMap.

Action Required:
Please review the changes and provide feedback. If any further enhancements are needed, let’s discuss them!

**Comment by Ahsankhalid618** [comment]
Your PR is merged Successfully. Thanks

**Comment by Ahsankhalid618** [comment]
Your PR is merged Successfully. Thanks
