### ISSUE TITLE
code od conduction.md

### ISSUE THREAD

**Issue by Mukesh-ghildiyal** [Ahsankhalid618/react-weather-app#9]

**Comment by danieltayal07** [comment]
hi sir hope you are good
is this issue available for hacktoberfest2024,
if yes i would love to make the code of conduct for the app!

**Comment by Mukesh-ghildiyal** [comment]
As it's an open source repository might be it's needed an code of conduct file. assign this task to me with hactoberfest tag

**Comment by Ahsankhalid618** [comment]
> As it's an open source repository might be it's needed an code of conduct file. assign this task to me with hactoberfest tag

Thanks, @Mukesh-ghildiyal. It's already assigned to another issue along with documentation, but if you have any other ideas, you can raise a new issue, and you will get assigned. Looking forward to your contributions. ❤️

Leave a 🌟 to the repo for future updates.
